require("lze").load {
  { import = "plugins.rose-pine" },
  { import = "plugins.lualine" },
  { import = "plugins.snacks-nvim" },
  { import = "plugins.noice" },
  { import = "plugins.blink-cmp" },
  { import = "plugins.lsp" },
  { import = "plugins.none-ls" },
  { import = "plugins.treesitter" },
  { import = "plugins.fzf-lua" },
  { import = "plugins.oil-nvim" },
  { import = "plugins.obsidian-nvim" },
  { import = "plugins.harpoon" },
  { import = "plugins.plenary" },
  { import = "plugins.gitblame" },
  { import = "plugins.neo-tree" },
  { import = "plugins.nvim-autopairs" },
  { import = "plugins.otter" },
  { import = "plugins.tmux-navigator" },
  { import = "plugins.trouble" },
  { import = "plugins.which-key" },
  { import = "plugins.ecolog" },
}
